/** Configuração isolada do módulo Viaturas/Frota. */

const FROTA_CONFIG = Object.freeze({
  VERSION: '2.3.1',
  SPREADSHEET_NAME: 'INTRANET_GCMP_FROTA',
  SPREADSHEET_PROPERTY: 'FROTA_SPREADSHEET_ID',
  ROOT_FOLDER_PROPERTY: 'FROTA_ROOT_FOLDER_ID',
  ROOT_FOLDER_ID: '169rQxF7JsCFtG6ercO0oKmfljUb1oYLK',
  TIME_ZONE: 'America/Sao_Paulo',
  MAX_UPLOAD_BYTES: 8 * 1024 * 1024,
  ALLOWED_FILE_EXTENSIONS: Object.freeze(['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx', 'xls', 'xlsx', 'csv', 'txt']),
  DEFAULT_ALERTS: Object.freeze({
    REVISAO_KM: 500,
    OLEO_KM: 300,
    SEGURO_DIAS: '30,15,7,1',
    LICENCIAMENTO_DIAS: '30,15,7,1',
    MANUTENCAO_DIAS: '15,7,1'
  }),
  PROPERTY_KEYS: Object.freeze({
    REVISAO_KM: 'FROTA_ALERTA_REVISAO_KM',
    OLEO_KM: 'FROTA_ALERTA_OLEO_KM',
    SEGURO_DIAS: 'FROTA_ALERTA_SEGURO_DIAS',
    LICENCIAMENTO_DIAS: 'FROTA_ALERTA_LICENCIAMENTO_DIAS',
    MANUTENCAO_DIAS: 'FROTA_ALERTA_MANUTENCAO_DIAS',
    POSICOES_PNEUS: 'FROTA_POSICOES_PNEUS_JSON'
  }),
  STATUS_VIATURA: Object.freeze(['DISPONIVEL', 'EM_USO', 'EM_MANUTENCAO', 'INDISPONIVEL', 'RESERVADA', 'SINISTRADA', 'BAIXADA', 'INATIVA']),
  TIPOS_OCORRENCIA: Object.freeze(['OBSERVACAO', 'DEFEITO', 'IRREGULARIDADE', 'LIMPEZA', 'DOCUMENTACAO', 'EQUIPAMENTO_AUSENTE', 'OUTRO']),
  CATEGORIAS_OCORRENCIA: Object.freeze(['MECANICA', 'ELETRICA', 'PNEUS', 'FREIOS', 'ILUMINACAO', 'LATARIA', 'MOTOR', 'SUSPENSAO', 'DIRECAO', 'EQUIPAMENTOS', 'LIMPEZA', 'DOCUMENTACAO', 'OUTRO']),
  GRAVIDADES: Object.freeze(['BAIXA', 'MEDIA', 'ALTA', 'VIATURA_SEM_CONDICOES_DE_USO']),
  POSICOES_PNEUS: Object.freeze(['DIANTEIRO_ESQUERDO', 'DIANTEIRO_DIREITO', 'TRASEIRO_ESQUERDO', 'TRASEIRO_DIREITO', 'ESTEPE']),
  ESTADOS_PNEUS: Object.freeze(['NOVO', 'BOM', 'ATENCAO', 'RUIM', 'CRITICO', 'RETIRADO']),
  CATEGORIAS_ARQUIVOS: Object.freeze(['CRLV', 'SEGURO', 'LICENCIAMENTO', 'NOTA_FISCAL', 'ORDEM_DE_SERVICO', 'ORCAMENTO', 'LAUDO', 'FOTO', 'MANUTENCAO', 'OUTRO']),
  SHEETS: Object.freeze({
    VIATURAS: Object.freeze([
      'ID_VIATURA', 'PREFIXO', 'PLACA', 'TIPO', 'MARCA', 'MODELO', 'ANO', 'COR', 'CHASSI', 'RENAVAM', 'COMBUSTIVEL', 'KM_ATUAL', 'STATUS', 'SETOR', 'DATA_AQUISICAO', 'OBSERVACAO_ATUAL', 'REVISAO_PROXIMA_KM', 'REVISAO_PROXIMA_DATA', 'REVISAO_TIPO', 'REVISAO_OBSERVACAO', 'SEGURO_SEGURADORA', 'SEGURO_APOLICE', 'SEGURO_INICIO', 'SEGURO_VENCIMENTO', 'SEGURO_OBSERVACAO', 'LICENCIAMENTO_ANO', 'LICENCIAMENTO_VENCIMENTO', 'LICENCIAMENTO_SITUACAO', 'LICENCIAMENTO_OBSERVACAO', 'OLEO_ULTIMA_TROCA_KM', 'OLEO_ULTIMA_TROCA_DATA', 'OLEO_PROXIMA_TROCA_KM', 'OLEO_PROXIMA_TROCA_DATA', 'OLEO_ESPECIFICACAO', 'OLEO_OBSERVACAO', 'PNEUS_RESUMO', 'MANUTENCAO_PROXIMA_KM', 'MANUTENCAO_PROXIMA_DATA', 'MANUTENCAO_PROXIMA_DESCRICAO', 'ID_PASTA_DRIVE', 'NOME_PASTA_DRIVE', 'ATIVO', 'MOVIMENTACAO_ATIVA_ID', 'ULTIMO_CONDUTOR', 'ULTIMO_CONDUTOR_MASP', 'ULTIMA_MOVIMENTACAO', 'CRIADO_EM', 'CRIADO_POR_MASP', 'ATUALIZADO_EM', 'ATUALIZADO_POR_MASP'
    ]),
    MOVIMENTACOES_KM: Object.freeze([
      'ID_MOVIMENTACAO', 'ID_VIATURA', 'PREFIXO', 'PLACA', 'CONDUTOR_MASP', 'CONDUTOR_NOME', 'DATA_HORA_ABERTURA', 'KM_SISTEMA_ABERTURA', 'KM_INICIAL_INFORMADO', 'KM_DIVERGENTE', 'JUSTIFICATIVA_DIVERGENCIA', 'OBSERVACAO_SAIDA', 'DATA_HORA_ENCERRAMENTO', 'KM_FINAL', 'KM_PERCORRIDO', 'OBSERVACAO_ENCERRAMENTO', 'STATUS', 'ENCERRADO_POR_MASP', 'ENCERRADO_POR_NOME', 'CRIADO_EM', 'ATUALIZADO_EM'
    ]),
    OBSERVACOES_VIATURAS: Object.freeze([
      'ID_OBSERVACAO', 'ID_VIATURA', 'ID_MOVIMENTACAO', 'PREFIXO', 'PLACA', 'TIPO', 'CATEGORIA', 'GRAVIDADE', 'OBSERVACAO_ANTERIOR', 'OBSERVACAO_NOVA', 'MOTIVO', 'INFORMADO_POR_MASP', 'INFORMADO_POR_NOME', 'DATA_HORA', 'ATIVO', 'ID_MANUTENCAO_VINCULADA'
    ]),
    DEFEITOS_VIATURAS: Object.freeze([
      'ID_DEFEITO', 'ID_VIATURA', 'ID_MOVIMENTACAO', 'PREFIXO', 'PLACA', 'CATEGORIA', 'GRAVIDADE', 'DESCRICAO', 'LOCAL_DEFEITO', 'SOLICITOU_RETIRADA', 'STATUS_DEFEITO', 'INFORMADO_POR_MASP', 'INFORMADO_POR_NOME', 'DATA_HORA_REGISTRO', 'PROVIDENCIA_ADOTADA', 'RESPONSAVEL_TRATAMENTO_MASP', 'RESPONSAVEL_TRATAMENTO_NOME', 'DATA_HORA_VISUALIZACAO', 'DATA_HORA_RESOLUCAO', 'OBSERVACAO_RESOLUCAO', 'ATIVO', 'ID_MANUTENCAO_VINCULADA'
    ]),
    MANUTENCOES: Object.freeze([
      'ID_MANUTENCAO', 'ID_VIATURA', 'PREFIXO', 'PLACA', 'TIPO_MANUTENCAO', 'CLASSIFICACAO', 'STATUS', 'DATA_ABERTURA', 'DATA_PREVISTA', 'DATA_INICIO', 'DATA_CONCLUSAO', 'KM_ABERTURA', 'KM_CONCLUSAO', 'OFICINA_FORNECEDOR', 'CNPJ_CPF_FORNECEDOR', 'DESCRICAO_PROBLEMA', 'SERVICO_REALIZADO', 'PECAS_SUBSTITUIDAS', 'VALOR_MAO_OBRA', 'VALOR_PECAS', 'VALOR_TOTAL', 'PROXIMA_MANUTENCAO_DATA', 'PROXIMA_MANUTENCAO_KM', 'OBSERVACAO', 'CRIADO_POR_MASP', 'CRIADO_POR_NOME', 'CRIADO_EM', 'ATUALIZADO_EM', 'ID_OCORRENCIA_ORIGEM', 'TIPO_OCORRENCIA_ORIGEM'
    ]),
    PNEUS: Object.freeze([
      'ID_PNEU', 'ID_VIATURA', 'PREFIXO', 'PLACA', 'POSICAO', 'MARCA', 'MODELO', 'MEDIDA', 'NUMERO_SERIE', 'DATA_INSTALACAO', 'KM_INSTALACAO', 'DATA_RETIRADA', 'KM_RETIRADA', 'ESTADO', 'PREVISAO_TROCA', 'MOTIVO_RETIRADA', 'OBSERVACAO', 'ATIVO', 'CRIADO_EM', 'ATUALIZADO_EM'
    ]),
    ARQUIVOS_VIATURAS: Object.freeze([
      'ID_REGISTRO', 'ID_VIATURA', 'PREFIXO', 'PLACA', 'ID_ARQUIVO_DRIVE', 'NOME_ARQUIVO', 'TIPO_ARQUIVO', 'TAMANHO_BYTES', 'CATEGORIA', 'DESCRICAO', 'DATA_DOCUMENTO', 'LINK_ARQUIVO', 'ENVIADO_POR_MASP', 'ENVIADO_POR_NOME', 'DATA_HORA_UPLOAD', 'ATIVO'
    ]),
    HISTORICO_FROTA: Object.freeze([
      'ID_HISTORICO', 'ID_VIATURA', 'PREFIXO', 'PLACA', 'TIPO_ACAO', 'CAMPO_ALTERADO', 'VALOR_ANTERIOR', 'VALOR_NOVO', 'JUSTIFICATIVA', 'USUARIO_MASP', 'USUARIO_NOME', 'DATA_HORA'
    ])
  }),
  PERMISSIONS: Object.freeze([
    ['FROTA_ACESSAR', 'acessar', 'Acessar o módulo Frota'],
    ['FROTA_VISUALIZAR_KM', 'visualizar_km', 'Visualizar a área Lançamento de KM'],
    ['FROTA_VISUALIZAR_VEICULOS', 'visualizar_veiculos', 'Visualizar os veículos cadastrados na Frota'],
    ['FROTA_VISUALIZAR_MANUTENCOES', 'visualizar_manutencoes', 'Visualizar a área Manutenções'],
    ['FROTA_VISUALIZAR_DEFEITOS', 'visualizar_defeitos', 'Visualizar a área Defeitos e observações'],
    ['FROTA_KM_ABRIR', 'km_abrir', 'Abrir utilização e lançar KM inicial'],
    ['FROTA_KM_ENCERRAR', 'km_encerrar', 'Encerrar utilização e lançar KM final'],
    ['FROTA_ENCERRAR_MOVIMENTACAO_OUTRO_USUARIO', 'km_encerrar_outro', 'Encerrar movimentação de outro usuário'],
    ['FROTA_VISUALIZAR_GERENCIAMENTO', 'visualizar_gerenciamento', 'Visualizar gerenciamento administrativo da frota'],
    ['FROTA_EDITAR_OBSERVACOES', 'editar_observacoes', 'Editar observação principal do veículo'],
    ['FROTA_VISUALIZAR_HISTORICO', 'visualizar_historico', 'Visualizar histórico completo da frota'],
    ['FROTA_CADASTRAR_VIATURA', 'cadastrar_veiculo', 'Cadastrar veículos na Frota'],
    ['FROTA_EDITAR_VIATURA', 'editar_veiculo', 'Editar dados dos veículos da Frota'],
    ['FROTA_EXCLUIR_VIATURA', 'excluir_veiculo', 'Desativar veículos da Frota'],
    ['FROTA_ALTERAR_STATUS', 'alterar_status', 'Alterar o status operacional dos veículos'],
    ['FROTA_VISUALIZAR_ARQUIVOS', 'visualizar_arquivos', 'Visualizar arquivos dos veículos'],
    ['FROTA_ENVIAR_ARQUIVOS', 'enviar_arquivos', 'Enviar arquivos para as pastas dos veículos'],
    ['FROTA_EXCLUIR_ARQUIVOS', 'excluir_arquivos', 'Excluir logicamente arquivos dos veículos'],
    ['FROTA_GERENCIAR_MANUTENCOES', 'gerenciar_manutencoes', 'Cadastrar e atualizar manutenções'],
    ['FROTA_GERENCIAR_PNEUS', 'gerenciar_pneus', 'Cadastrar e atualizar pneus'],
    ['FROTA_TRATAR_DEFEITOS', 'tratar_defeitos', 'Visualizar e tratar defeitos'],
    ['FROTA_RECEBER_NOTIFICACOES', 'receber_notificacoes', 'Receber notificações automáticas da frota']
  ])
});

const FROTA_NOTIFICATION_HEADERS = Object.freeze([
  'ID', 'ID_USUARIO', 'TIPO', 'TITULO', 'MENSAGEM', 'GRAVIDADE', 'MODULO', 'ID_REGISTRO', 'DESTINATARIO', 'PERMISSAO_DESTINATARIA', 'LIDA', 'LIDA_EM', 'RESOLVIDA', 'DATA_RESOLUCAO', 'CRIADO_EM', 'CRIADA_POR', 'CHAVE_UNICA'
]);
