import { randomUUID } from 'node:crypto';
import { pool } from '../config/db.js';
import { hashPassword } from '../lib/security.js';

const permissionCatalog=[
['dashboard.visualizar','dashboard','visualizar','Visualizar painel'],
['usuarios.visualizar','usuarios','visualizar','Visualizar usuários'],['usuarios.criar','usuarios','criar','Cadastrar usuários'],['usuarios.editar','usuarios','editar','Editar usuários e redefinir senha'],['usuarios.gerenciar_permissoes','usuarios','gerenciar_permissoes','Gerenciar permissões individuais e em massa'],
['pessoal.visualizar','pessoal','visualizar','Visualizar pessoal'],['pessoal.criar','pessoal','criar','Cadastrar pessoal'],['pessoal.editar','pessoal','editar','Editar pessoal e analisar solicitações cadastrais'],
['patrimonio.visualizar','patrimonio','visualizar','Visualizar patrimônio'],['patrimonio.criar','patrimonio','criar','Cadastrar patrimônio'],['patrimonio.editar','patrimonio','editar','Editar patrimônio'],['patrimonio.cautelas.visualizar','patrimonio','cautelas_visualizar','Visualizar cautelas e termos'],['patrimonio.cautelas.criar','patrimonio','cautelas_criar','Criar cautelas'],['patrimonio.cautelas.devolver','patrimonio','cautelas_devolver','Registrar devoluções parciais e totais'],['patrimonio.cautelas.prorrogar','patrimonio','cautelas_prorrogar','Prorrogar cautelas'],['patrimonio.cautelas.cancelar','patrimonio','cautelas_cancelar','Cancelar cautelas'],['patrimonio.cautelas.administrativa','patrimonio','cautelas_administrativa','Gerenciar cautelas administrativas'],
['frota.visualizar','frota','visualizar','Visualizar frota'],['frota.gerenciar','frota','gerenciar','Gerenciar operações excepcionais da frota'],['frota.viaturas.criar','frota','viaturas_criar','Cadastrar viaturas'],['frota.viaturas.editar','frota','viaturas_editar','Editar viaturas'],['frota.km.registrar','frota','km_registrar','Registrar quilometragem'],['frota.turnos.iniciar','frota','turnos_iniciar','Iniciar turno de viatura'],['frota.turnos.encerrar','frota','turnos_encerrar','Encerrar turno de viatura'],['frota.defeitos.visualizar','frota','defeitos_visualizar','Visualizar defeitos'],['frota.defeitos.criar','frota','defeitos_criar','Registrar defeitos'],['frota.defeitos.resolver','frota','defeitos_resolver','Resolver defeitos'],['frota.manutencoes.visualizar','frota','manutencoes_visualizar','Visualizar manutenções'],['frota.manutencoes.gerenciar','frota','manutencoes_gerenciar','Abrir e concluir manutenções'],['frota.pneus.visualizar','frota','pneus_visualizar','Visualizar pneus'],['frota.pneus.gerenciar','frota','pneus_gerenciar','Instalar e remover pneus'],
['documentos.visualizar','documentos','visualizar','Visualizar documentos'],['documentos.criar','documentos','criar','Cadastrar documentos'],['recompensas.visualizar','recompensas','visualizar','Visualizar recompensas'],['recompensas.criar','recompensas','criar','Cadastrar recompensas'],['auditoria.visualizar','auditoria','visualizar','Visualizar auditoria'],['configuracoes.gerenciar','configuracoes','gerenciar','Gerenciar configurações e diagnóstico']
];
async function ensurePermissions(){for(const[codigo,modulo,acao,descricao]of permissionCatalog)await pool.execute(`INSERT INTO permissoes (id,codigo,modulo,acao,descricao,ativa) VALUES (?,?,?,?,?,1) ON DUPLICATE KEY UPDATE modulo=VALUES(modulo),acao=VALUES(acao),descricao=VALUES(descricao),ativa=1`,[randomUUID(),codigo,modulo,acao,descricao]);}
async function ensureDefaults(){for(const item of [['NOME_SISTEMA',process.env.APP_NAME||'Intranet GCMP','Nome exibido no sistema'],['NOME_INSTITUICAO',process.env.INSTITUTION_NAME||'Guarda Civil Municipal de Passos','Nome da instituição'],['CAUTELA_SEQUENCIAL','1','Sequencial dos termos de cautela']])await pool.execute('INSERT INTO configuracoes (chave,valor,descricao) VALUES (?,?,?) ON DUPLICATE KEY UPDATE descricao=VALUES(descricao)',item);}
async function ensureAdmin(){const masp=String(process.env.ADMIN_MASP||'').replace(/\D/g,''),name=process.env.ADMIN_NAME||'Administrador do Sistema',email=process.env.ADMIN_EMAIL||'admin@instituicao.local',password=process.env.ADMIN_PASSWORD||'';console.log(`[BOOTSTRAP] ADMIN_MASP definido: ${Boolean(masp)} | ADMIN_PASSWORD definido: ${Boolean(password)}`);if(!masp||!password){console.warn('[BOOTSTRAP] ADMIN_MASP/ADMIN_PASSWORD não definidos. Administrador não será criado.');return{created:false,reason:'missing_admin_env'};}const[existing]=await pool.execute('SELECT id FROM usuarios WHERE masp=? LIMIT 1',[masp]);let userId=existing[0]?.id,created=false;if(!userId){userId=randomUUID();const passwordHash=await hashPassword(password);await pool.execute(`INSERT INTO usuarios (id,masp,nome,email,cargo,funcao,setor,status,senha_hash,trocar_senha) VALUES (?,?,?,?,'Administrador','Administrador do Sistema','Administrativo','ATIVO',?,1)`,[userId,masp,name,email,passwordHash]);created=true;}const[permissions]=await pool.query('SELECT id FROM permissoes WHERE ativa=1');for(const permission of permissions)await pool.execute(`INSERT INTO usuario_permissoes (id,id_usuario,id_permissao,permitido,concedido_por) VALUES (?,?,?,1,'BOOTSTRAP') ON DUPLICATE KEY UPDATE permitido=1,concedido_por='BOOTSTRAP',concedido_em=NOW()`,[randomUUID(),userId,permission.id]);return{created,userId,masp,permissions:permissions.length};}
export async function bootstrapDatabase(){console.log('[BOOTSTRAP] Iniciando verificação do banco...');await pool.query('SELECT 1');await ensurePermissions();await ensureDefaults();const admin=await ensureAdmin();console.log('[BOOTSTRAP] Banco verificado com sucesso.');return{ok:true,admin};}
